### ISSUE TITLE
A Wordle-like score sharing

### ISSUE THREAD

**Issue by DenisovichDev** [CodingTrain/Directional-Boring#35]
@shiffman mentioned this in today's stream. I wonder how this could be implemented.

**Comment by alin256** [comment]
I have an idea how to make score sharing (I have implemented it for another project) but I did not play wordless so I do not know what kind of sharing is used there.

**Comment by DenisovichDev** [comment]
Basically it copies your scores in your clipboard to share with a friend, in a creative way. Check out how Wordle does it, maybe we can do something similar

**Comment by alin256** [comment]
I think, I have that covered. But probably not before the weekend.

**Comment by alin256** [comment]
@DenisovichDev do you mean something like that:

Wordle 390 6/6

⬛⬛🟨⬛⬛
⬛🟨🟨⬛⬛
⬛🟨⬛⬛⬛
⬛⬛🟨🟨⬛
🟨🟨⬛⬛⬛
🟩🟩🟩🟩🟩

**Comment by DenisovichDev** [comment]
Yes something based on this. Do you have any ideas?

**Comment by DenisovichDev** [comment]
The idea is that there would be link to the game with it as well, so that people can challenge their friends to play

**Comment by alin256** [comment]
I was thinking to share action sequences as one idea. Like

* **start** ➡️
* **drill one pipe** *did not find emoji*
* **stuck** ???
* **pull back** ↩️ followed by a *line break*
* **side track** up ⤴️ or down ⤵️
* **win** 🎯 or 💰
* **lose** 💸 ??? 🥉🔜???

**Comment by alin256** [comment]
> The idea is that there would be link to the game with it as well, so that people can challenge their friends to play

I know how to make pre-filled copy, twitter, linkedin, etc posts with a button.

**Comment by alin256** [comment]
> * **drill one pipe** _did not find emoji_
> * **stuck** ???

what if we use dashes with a * (best middle of line *) in the end
like:

➡️——-*↩️
⤵️——————-*🎯

**Comment by DenisovichDev** [comment]
That looks like a good idea! I'll try to make a window, see how it works out. A bit busy this week but I'll try

**Comment by alin256** [comment]
I implemented the loading of replays but only limited to steering (no pullbacks).

Currently working to display scores right.

**Comment by alin256** [comment]
I implemented the basic replays that show the last well but the correct sharable score.

Just press Start:

https://al-digital.no/Directional-Boring/?seed=767646&sol=//////////8PAAAAAAAAAAAAAAAAAAAAAAAAAA==&sup=AS0DAQI=

**Comment by DenisovichDev** [comment]
@alin256 Okay that is super cool! I wasn't thinking about replays at all, but this is really great

**Comment by alin256** [comment]
@DenisovichDev @shiffman I managed a shorter URL and all actions.

https://al-digital.no/Directional-Boring/?seed=541856&s4=/qbQBfz85E4Pavz8vHa05uQ=

The buttons are not blocked from a user during a replay, though.
The interface now lacks a "retry" button.

**Comment by alin256** [comment]
I have played with the interface for the last week. I think we will be better off with less freedom and suggest replacing sliders with a few pre-sets. 

The reason is that the user should not change the controls during a single game. In that respect, reloading, the interface with a button or a link, seems more intuitive than a slider. 

With the simulation parameters set consistently, the replay functionality works for all different settings when specified explicitly in the link.
https://al-digital.no/Directional-Boring/?rnd=3&seed=101244&ropd=2&s4=/rL8/CzmvPL8/NSW0Af8/P5y/Pzwzg==

@DenisovichDev @shiffman should we integrate the updated interface into [CodingTrain/Directional-Boring](https://github.com/CodingTrain/Directional-Boring)?

<img width="628" alt="Screenshot 2022-08-01 at 09 32 55" src="https://user-images.githubusercontent.com/7563037/182101257-98c03780-a463-4cb5-bccb-6758886bf736.png">

**Comment by DenisovichDev** [comment]
I love this!! Amazing work @alin256, I'm totally in favour of merging this. I have some ideas that I wanna try to implement to make it easier for the player to understand the UI, I'll work on it in the next few days.

So I would say you should merge this, I'll fix the CSS and stuff and work on some other UX related stuff.

Also, here's my replay of that level:
https://al-digital.no/Directional-Boring/?rnd=3&seed=101244&ropd=2&s4=/rb8/JD+Lvw81vz8/GT+Bvz8QM7s
