### ISSUE TITLE
Levels of Difficulty

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Directional-Boring#4]
Practice
* You see everything and have full control

Hard
* You only have access to
     * depth
     * distance to exit
     * distance to nearest obstacle

**Comment by gradyh** [comment]
To make "Hard Mode" more realistic, maybe you could only see the obstacles and geologic layers on the screen with horizontal and vertical scales (as if you had a map of existing utilities and geology), and you have to cross-reference to your real-time depth and distance measurements. Super-hard mode would be use continuous drill advance :)

**Comment by kfahn22** [comment]
I have a somewhat working version at this point, although it still has a couple of issues.  I like the idea of adding utilities, etc.  Grady, do you have an example?  I have tried to incorporate HARD mode into your version.  At this point, I have it on HARD mode because I can't figure out how to stop the obstacles from showing on HARD mode (maybe it has something to do with hddScene?).   Here is the latest version if you want to check out.  FYI, I added code to prevent obstacles from being added to water, but it causes an error if all of the random positions end up within the ellipse.
https://editor.p5js.org/kfahn/sketches/5J0UPtvDL

**Comment by aerger** [comment]
One thought I had would be something along the lines of a "fog of war" other games use, simulating real-time scanning, that only reveals a small area around or slightly ahead of the drill head, and you'd have to react appropriately to any suddenly-appearing obstacles if you can, given the limited turning radius of your drill head.  I assume there's scanning and mapping done  well ahead of time IRL, of course, but this might a fun twist.

**Comment by alin256** [comment]
> "fog of war"

I did a totally unrelated research prototype about directional drilling a while back.
Mine has uncertainty visualization of subsurface, but the implementation is a bit involved. 
Try it out if you are interested to get some inspiration: http://game.geosteering.no

![image](https://user-images.githubusercontent.com/7563037/177400307-3a40e11e-25af-4dbf-af66-ce8a33934d50.png)

PS: if the server fails, which it does occasionally, ping me to restart it.

**Comment by ArztKlein** [comment]
Perhaps on this practice mode there could be a curve showing where the drill will be in the future if the bias is kept enabled/disabled?

**Comment by alin256** [comment]
I tried to groom the issue list.

@shiffman, do you think we can close this issue?

**Comment by shiffman** [comment]
Yes! We can open new issues for specific bugs or enhancements, thank you!!
